version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-10-07T15-07-38Z
    container_name: trunk-minio
    networks:
      - trunk-network
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - trunk-minio-data:/data
    environment:
    - MINIO_ROOT_USER=admin
    - MINIO_ROOT_PASSWORD=M!Secr3t
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  trunk-minio-data:

networks:
  trunk-network:
    external: true
