version: '3.7'

services:
  minio:
    image: tientq/jupyter-pyspark:3.4.1
    container_name: trunk-jupyter
    networks:
      - trunk-network
    ports:
    - 8888:8888
    - 4041:4041
    volumes:
    - trunk-jupyter:/home/jovyan
    - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    environment:
    - GRANT_SUDO=yes
    user: root

volumes:
  trunk-jupyter:

networks:
  trunk-network:
    external: true
