services:
  kafka:
    image: docker.io/bitnami/kafka:3.9
    container_name: trunk-kafka
    ports:
      - "9092:9092"
    networks:
      - trunk-network
    volumes:
      - trunk-kafka-data:/bitnami
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    container_name: trunk-schema-registry
    hostname: schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: NONE
    depends_on:
      - kafka
    networks:
      - trunk-network
    ports:
      - 8081:8081

  debezium:
    image: tientq/debezium-connect:3.0.4
    build:
      context: ../docker/debezium-connect
    container_name: trunk-debezium-connect
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: _debezium.configs
      OFFSET_STORAGE_TOPIC: _debezium.offsets
      STATUS_STORAGE_TOPIC: _debezium.statuses
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
    networks:
      - trunk-network
    ports:
      - 8083:8083

  conduktor-db:
    image: postgres:14
    container_name: trunk-kafka-conduktor-db
    networks:
      - trunk-network
    volumes:
      - trunk-conduktor-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "M!Secr3t"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor:
    image: conduktor/conduktor-console:1.26.0
    container_name: trunk-kafka-conduktor-console
    depends_on:
      - conduktor-db
    networks:
      - trunk-network
    ports:
      - "8080:8080"
    volumes:
      - trunk-conduktor-console-data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:M!Secr3t@conduktor-db:5432/conduktor-console"
      CDK_CLUSTERS_0_ID: "default"
      CDK_CLUSTERS_0_NAME: "My Local Kafka Cluster"
      CDK_CLUSTERS_0_COLOR: "#0013E7"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "PLAINTEXT://kafka:9092"
      CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://schema-registry:8081"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_URL: "http://debezium:8083"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_NAME: "debezium-connect"

volumes:
  trunk-kafka-data:
  trunk-conduktor-console-data:
  trunk-conduktor-db-data:

networks:
  trunk-network:
    external: true
