version: '3.7'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    container_name: trunk-mysql
    networks:
      - trunk-network
    ports:
      - 3306:3306
    volumes:
      - trunk-mysql-data:/bitnami/mysql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=M!Secr3t
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  trunk-mysql-data:

networks:
  trunk-network:
    external: true
